const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  STAFF: "staff",
};

const CATEGORIES = {
  ANALGESICS: "Analgesics",
  ANTACIDS: "Antacids",
  ANTIANXIETY: "Antianxiety Drugs",
  ANTIARRHYTHMICS: "Antiarrhythmics",
  ANTIBACTERIALS: "Antibacterials",
  ANTIBIOTICS: "Antibiotics",
  ANTICOAGULANTS_THROMBOLYTICS: "Anticoagulants and Thrombolytics",
  ANTICONVULSANTS: "Anticonvulsants",
  ANTIDEPRESSANTS: "Antidepressants",
  ANTIDIARRHEALS: "Antidiarrheals",
  ANTIEMETICS: "Antiemetics",
  ANTIFUNGALS: "Antifungals",
  ANTIHISTAMINES: "Antihistamines",
  ANTIHYPERTENSIVES: "Antihypertensives",
  ANTI_INFLAMMATORIES: "Anti-Inflammatories",
  ANTINEOPLASTICS: "Antineoplastics",
  ANTIPSYCHOTICS: "Antipsychotics",
  ANTIPYRETICS: "Antipyretics",
  ANTIVIRALS: "Antivirals",
  BARBITURATES: "Barbiturates",
  BETA_BLOCKERS: "Beta-Blockers",
  BRONCHODILATORS: "Bronchodilators",
  COLD_CURES: "Cold Cures",
  CORTICOSTEROIDS: "Corticosteroids",
  COUGH_SUPPRESSANTS: "Cough Suppressants",
  CYTOTOXICS: "Cytotoxics",
  DECONGESTANTS: "Decongestants",
  DIURETICS: "Diuretics",
  EXPECTORANTS: "Expectorants",
  HORMONES: "Hormones",
  HYPOGLYCEMICS: "Hypoglycemics (Oral)",
  IMMUNOSUPPRESSIVES: "Immunosuppressives",
  LAXATIVES: "Laxatives",
  MUSCLE_RELAXANTS: "Muscle Relaxants",
  FEMALE_SEX_HORMONES: "Sex Hormones (Female)",
  MALE_SEX_HORMONES: "Sex Hormones (Male)",
  VITAMINS: "Vitamins",
};

export { ROLES, CATEGORIES };
